// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKCyWVj0zqgZCeMo3HuBhuMH255ebMec',
    appId: '1:481789490811:web:7181e125616c0750f354de',
    messagingSenderId: '481789490811',
    projectId: 'projectgargi-1d54f',
    authDomain: 'projectgargi-1d54f.firebaseapp.com',
    databaseURL: 'https://projectgargi-1d54f-default-rtdb.firebaseio.com',
    storageBucket: 'projectgargi-1d54f.appspot.com',
    measurementId: 'G-33PXP1YEPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvC9y6bz6F717C9VkOt8TSZQiUoFpdfK8',
    appId: '1:481789490811:android:5e3aa0bca8ebc476f354de',
    messagingSenderId: '481789490811',
    projectId: 'projectgargi-1d54f',
    databaseURL: 'https://projectgargi-1d54f-default-rtdb.firebaseio.com',
    storageBucket: 'projectgargi-1d54f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPLfZFzre4y6-AHXaQvfcvpDFtTpiA5BU',
    appId: '1:481789490811:ios:9ae8a05cab6bdc7ff354de',
    messagingSenderId: '481789490811',
    projectId: 'projectgargi-1d54f',
    databaseURL: 'https://projectgargi-1d54f-default-rtdb.firebaseio.com',
    storageBucket: 'projectgargi-1d54f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPLfZFzre4y6-AHXaQvfcvpDFtTpiA5BU',
    appId: '1:481789490811:ios:efd8aa57c7b0d7c5f354de',
    messagingSenderId: '481789490811',
    projectId: 'projectgargi-1d54f',
    databaseURL: 'https://projectgargi-1d54f-default-rtdb.firebaseio.com',
    storageBucket: 'projectgargi-1d54f.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
